POST http://localhost:3009/categories/create
Content-Type: application/json

{
  "userId": "66b9e64fe59cece120bf3c63",
  "title": "Suits mens",
  "categories": "men",
  "description": "Suit for men",
  "photo": "https://th.bing.com/th/id/OIP.Xt5_b3Q8Q07kjdT1bfuP2wAAAA?rs=1&pid=ImgDetMain"
}


### edit category
PUT http://localhost:3009/categories/edit
Content-Type: application/json

 {
      "categoryId":"66e9731a2b2018183fceea7f",
      "userId":"66b9e64fe59cece120bf3c63",
      "title":"khalilhaouas",
      "categories":"women",
      "description":"neu model 2024",
      "photo":"https://th.bing.com/th/id/OPEC.7ZSFWSV1pykp1w474C474?w=200&h=220&rs=1&o=5&dpr=1.1&pid=21.1"
 }

### delete category
   DELETE http://localhost:3009/categories/delete
Content-Type: application/json
   
 {
   "userId":"66b9e64fe59cece120bf3c63",
   "categoryId":"66be5a71e74edb87276bc53c"
 }

### get all categories
   GET http://localhost:3009/categories/getAll
Content-Type: application/json
   
 