### Redgister User
 POST http://localhost:3009/users/register 
 Content-Type: application/json

 {
    "firstName":"khalil",
    "lastName":"akrami",
    "email":"amene@gmail.com",
    "password":"123456",
    "confirmPassword":"123456",
    "gender":"male",
    "telephone":"1234567"
}


#### Login User
POST http://localhost:3009/users/login
Content-Type: application/json

{
    "email":"amene@gmail.com",
    "password":"123456"
}